services:
  - type: web
    name: sync-tool-feature-flag
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DEBUG
        value: "false"
